name: Go

on:
  create:
    tags:
      - v*
      - v-v*

jobs:

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Go mod tidy checker
        id: gomodtidy
        uses: ./.github/actions/gomodtidy

      - name: Gofmt checker
        id: gofmt
        uses: ./.github/actions/gofmt
        with:
          path: ./

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        # Use blst tag to allow go and bazel builds for blst.
        run: |
          mkdir builds &&
          go build -v --tags=blst_enabled -o ./builds ./...

#      # Tests run via Bazel for now...
#      - name: Test
#        run: go test -v --tags=develop,blst_enabled ./...

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            ./builds/beacon-chain
            ./builds/validator
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Request Multinet Upgrade
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          export GH_TAG=${GITHUB_REF/refs\/tags\//} &&
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type":"upgrade dev", "client_payload": {"repository": "VANGUARD", "tag": "'$GH_TAG'"}}' \
          -u "$GITHUB_TOKEN" \
          https://api.github.com/repos/lukso-network/l16-multinet/dispatches   

