name: Build and Release

on:
  push:
    branches:
      - 'feature/github-actions-ci-cd'

jobs:
  release:
    strategy:
      matrix:
        go-version: [ 1.16 ]
        platform: [ windows-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Cache bazelisk download
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: ~/.cache/bazelisk
          key: ${{ matrix.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ matrix.os }}-${{ env.cache-name }}-development

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build beacon-chain client
        run: bazel build //beacon-chain