name: Test

on:
  push:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16 ]
        platform: [ ubuntu-18.04 ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bazel test all
        run: |
          bazel test //...